import { name } from '../package.json'

export function withComment(content: string) {
  return `# ${content}`
}

export function withNewLine(content: string) {
  return `\r${content}`
}

export function Sign() {
  return withComment(`generated by ${name}`)
}

export function isBasic(type: string) {
  return type === 'basic'
}
