export function withComment(content: string) {
  return `# ${content}`
}

export function withNewLine(content: string) {
  return `\r${content}`
}

export function Sign() {
  return withComment('generated by @alexzhang1030/gi')
}

export function isBasic(type: string) {
  return type === 'basic'
}
